INSERT INTO articles (title, alias, content, user_id, updated_time, published, article_image, article_type)
VALUES ('Latest Smartphone Releases', 'latest-smartphone-releases',
        'Explore the latest smartphones that hit the market this month.', 1, '2024-10-01', TRUE,
        'smartphone-releases.png', 'NAVIGATION'),
       ('Top 10 Laptops for 2024', 'top-10-laptops-2024',
        'A review of the best laptops to buy in 2024 for work and gaming.', 1, '2024-10-02', TRUE, 'top-laptops.png',
        'FOOTER'),
       ('Smart Home Devices', 'smart-home-devices',
        'Discover the latest smart home devices that can make your life easier.', 2, '2024-10-03', TRUE,
        'smart-home-devices.png', 'NAVIGATION'),
       ('Gaming Accessories You Need', 'gaming-accessories-you-need',
        'Check out the must-have accessories for every gamer.', 2, '2024-10-04', TRUE, 'gaming-accessories.png',
        'PROMOTION'),
       ('Budget-Friendly Tablets', 'budget-friendly-tablets',
        'Top 5 affordable tablets for students and professionals.', 1, '2024-10-05', TRUE, 'budget-tablets.png',
        'NAVIGATION'),
       ('Wireless Earbuds Review', 'wireless-earbuds-review',
        'A comparison of the best wireless earbuds available in 2024.', 3, '2024-10-06', FALSE, 'wireless-earbuds.png',
        'FOOTER'),
       ('4K TVs: What to Look For', '4k-tvs-what-to-look-for', 'Everything you need to know before buying a 4K TV.', 1,
        '2024-10-07', TRUE, '4k-tvs.png', 'PROMOTION'),
       ('The Rise of Electric Scooters', 'rise-of-electric-scooters',
        'Explore the benefits and features of electric scooters.', 4, '2024-10-08', TRUE, 'electric-scooters.png',
        'FOOTER'),
       ('Best Drones for Photography', 'best-drones-photography',
        'Review of the top drones for stunning aerial photography.', 2, '2024-10-09', TRUE, 'drones-photography.png',
        'NAVIGATION'),
       ('Ultimate Guide to Gaming PCs', 'ultimate-guide-gaming-pcs',
        'Everything you need to know about building or buying a gaming PC.', 3, '2024-10-10', FALSE,
        'gaming-pc-guide.png', 'PROMOTION');

INSERT INTO articles (title, alias, content, user_id, updated_time, published, article_image, article_type)
VALUES ('Best Budget Laptops', 'best-budget-laptops', 'Find out the best budget laptops for everyday use.', 2,
        '2024-10-11', TRUE, 'budget-laptops.png', 'FOOTER'),
       ('Home Office Essentials', 'home-office-essentials', 'Essential gadgets and furniture for your home office.', 4,
        '2024-10-12', TRUE, 'home-office.png', 'FOOTER'),
       ('Top Fitness Gadgets', 'top-fitness-gadgets', 'Stay fit with these top fitness gadgets of 2024.', 3,
        '2024-10-13', TRUE, 'fitness-gadgets.png', 'FOOTER'),
       ('Affordable 4K Monitors', 'affordable-4k-monitors', 'Explore the best affordable 4K monitors.', 1, '2024-10-14',
        TRUE, '4k-monitors.png', 'FOOTER');
