INSERT INTO countries (name, code, currency_id) VALUES ('Afghanistan', 'AF', 1);
INSERT INTO countries (name, code, currency_id) VALUES ('Aland Islands', 'AX', 1);
INSERT INTO countries (name, code, currency_id) VALUES ('Albania', 'AL', 1);
INSERT INTO countries (name, code, currency_id) VALUES ('Algeria', 'DZ', 1);
INSERT INTO countries (name, code, currency_id) VALUES ('American Samoa', 'AS', 1);
INSERT INTO countries (name, code, currency_id) VALUES ('Andorra', 'AD', 1);
INSERT INTO countries (name, code, currency_id) VALUES ('Angola', 'AO', 1);
INSERT INTO countries (name, code, currency_id) VALUES ('Anguilla', 'AI', 1);
INSERT INTO countries (name, code, currency_id) VALUES ('Antarctica', 'AQ', 1);
INSERT INTO countries (name, code, currency_id) VALUES ('Antigua And Barbuda', 'AG', 1);

INSERT INTO states (name, country_id) VALUES ('Badakhshan', 1);
INSERT INTO states (name, country_id) VALUES ('Kabul', 1);
INSERT INTO states (name, country_id) VALUES ('Mirditë District', 2);
INSERT INTO states (name, country_id) VALUES ('Durrës District', 2);
INSERT INTO states (name, country_id) VALUES ('Timimoun', 3);
INSERT INTO states (name, country_id) VALUES ('Touggourt', 3);
INSERT INTO states (name, country_id) VALUES ('Ordino', 4);
INSERT INTO states (name, country_id) VALUES ('Escaldes-Engordany', 5);
INSERT INTO states (name, country_id) VALUES ('Luanda Province', 6);
INSERT INTO states (name, country_id) VALUES ('Lunda Norte Province', 7);
INSERT INTO states (name, country_id) VALUES ('Saint Peter Parish', 8);
INSERT INTO states (name, country_id) VALUES ('Saint Paul Parish', 9);