INSERT INTO countries (name, code, currency_id) VALUES ('Australia', 'AU', 10);
INSERT INTO countries (name, code, currency_id) VALUES ('Austria', 'AT', 2);
INSERT INTO countries (name, code, currency_id) VALUES ('Belgium', 'BE', 2);
INSERT INTO countries (name, code, currency_id) VALUES ('Brazil', 'BR', 24);
INSERT INTO countries (name, code, currency_id) VALUES ('Bulgaria', 'BG', 26);
INSERT INTO countries (name, code, currency_id) VALUES ('Canada', 'CA', 30);
INSERT INTO countries (name, code, currency_id) VALUES ('Croatia', 'HR', 39);
INSERT INTO countries (name, code, currency_id) VALUES ('Cyprus', 'CY', 2);
INSERT INTO countries (name, code, currency_id) VALUES ('Czech Republic', 'CZ', 41);
INSERT INTO countries (name, code, currency_id) VALUES ('Denmark', 'DK', 42);
INSERT INTO countries (name, code, currency_id) VALUES ('Estonia', 'EE', 2);
INSERT INTO countries (name, code, currency_id) VALUES ('Finland', 'FI', 2);
INSERT INTO countries (name, code, currency_id) VALUES ('France', 'FR', 2);
INSERT INTO countries (name, code, currency_id) VALUES ('Germany', 'DE', 2);
INSERT INTO countries (name, code, currency_id) VALUES ('Ghana Extended network', 'GH', 52);
INSERT INTO countries (name, code, currency_id) VALUES ('Gibraltar', 'GI', 53);
INSERT INTO countries (name, code, currency_id) VALUES ('Greece', 'GR', 2);
INSERT INTO countries (name, code, currency_id) VALUES ('Hong Kong', 'HK', 59);
INSERT INTO countries (name, code, currency_id) VALUES ('Hungary', 'HU', 60);
INSERT INTO countries (name, code, currency_id) VALUES ('India Invite only', 'IN', 62);
INSERT INTO countries (name, code, currency_id) VALUES ('Indonesia Invite only', 'ID', 63);
INSERT INTO countries (name, code, currency_id) VALUES ('Ireland', 'IE', 2);
INSERT INTO countries (name, code, currency_id) VALUES ('Italy', 'IT', 2);
INSERT INTO countries (name, code, currency_id) VALUES ('Japan', 'JP', 68);
INSERT INTO countries (name, code, currency_id) VALUES ('Kenya Extended network', 'KE', 71);
INSERT INTO countries (name, code, currency_id) VALUES ('Latvia', 'LV', 2);
INSERT INTO countries (name, code, currency_id) VALUES ('Liechtenstein', 'LI', 2);
INSERT INTO countries (name, code, currency_id) VALUES ('Lithuania', 'LT', 2);
INSERT INTO countries (name, code, currency_id) VALUES ('Luxembourg', 'LU', 2);
INSERT INTO countries (name, code, currency_id) VALUES ('Malaysia', 'MY', 84);
INSERT INTO countries (name, code, currency_id) VALUES ('Malta', 'MT', 2);
INSERT INTO countries (name, code, currency_id) VALUES ('Mexico', 'MX', 88);
INSERT INTO countries (name, code, currency_id) VALUES ('Netherlands', 'NL', 2);
INSERT INTO countries (name, code, currency_id) VALUES ('New Zealand', 'NZ', 96);
INSERT INTO countries (name, code, currency_id) VALUES ('Nigeria Extended network', 'NG', 98);
INSERT INTO countries (name, code, currency_id) VALUES ('Norway', 'NO', 99);
INSERT INTO countries (name, code, currency_id) VALUES ('Poland', 'PL', 107);
INSERT INTO countries (name, code, currency_id) VALUES ('Portugal', 'PT', 2);
INSERT INTO countries (name, code, currency_id) VALUES ('Romania', 'RO', 109);
INSERT INTO countries (name, code, currency_id) VALUES ('Singapore', 'SG', 119);
INSERT INTO countries (name, code, currency_id) VALUES ('Slovakia', 'SK', 2);
INSERT INTO countries (name, code, currency_id) VALUES ('Slovenia', 'SI', 2);
INSERT INTO countries (name, code, currency_id) VALUES ('South Africa Extended network', 'ZA', 122);
INSERT INTO countries (name, code, currency_id) VALUES ('Spain', 'ES', 2);
INSERT INTO countries (name, code, currency_id) VALUES ('Sweden', 'SE', 127);
INSERT INTO countries (name, code, currency_id) VALUES ('Switzerland', 'CH', 128);
INSERT INTO countries (name, code, currency_id) VALUES ('Thailand', 'TH', 133);
INSERT INTO countries (name, code, currency_id) VALUES ('United Arab Emirates', 'AE', 141);
INSERT INTO countries (name, code, currency_id) VALUES ('United Kingdom', 'GB', 53);
INSERT INTO countries (name, code, currency_id) VALUES ('United States', 'US', 5);
