INSERT INTO countries (name, code) VALUES ('Afghanistan', 'AFG');
INSERT INTO countries (name, code) VALUES ('Albania', 'ALB');
INSERT INTO countries (name, code) VALUES ('Algeria', 'DZA');
INSERT INTO countries (name, code) VALUES ('Andorra', 'AND');
INSERT INTO countries (name, code) VALUES ('Angola', 'AGO');
INSERT INTO countries (name, code) VALUES ('Antigua and Barbuda', 'ATG');
INSERT INTO countries (name, code) VALUES ('Argentina', 'ARG');
INSERT INTO countries (name, code) VALUES ('Armenia', 'ARM');
INSERT INTO countries (name, code) VALUES ('Australia', 'AUS');
INSERT INTO countries (name, code) VALUES ('Austria', 'AUT');
INSERT INTO countries (name, code) VALUES ('Azerbaijan', 'AZE');
INSERT INTO countries (name, code) VALUES ('Bahamas', 'BHS');
INSERT INTO countries (name, code) VALUES ('Bahrain', 'BHR');
INSERT INTO countries (name, code) VALUES ('Bangladesh', 'BGD');
INSERT INTO countries (name, code) VALUES ('Barbados', 'BRB');
INSERT INTO countries (name, code) VALUES ('Belarus', 'BLR');
INSERT INTO countries (name, code) VALUES ('Belgium', 'BEL');
INSERT INTO countries (name, code) VALUES ('Belize', 'BLZ');
INSERT INTO countries (name, code) VALUES ('Benin', 'BEN');
INSERT INTO countries (name, code) VALUES ('Bhutan', 'BTN');
INSERT INTO countries (name, code) VALUES ('Bolivia', 'BOL');
INSERT INTO countries (name, code) VALUES ('Bosnia and Herzegovina', 'BIH');
INSERT INTO countries (name, code) VALUES ('Botswana', 'BWA');
INSERT INTO countries (name, code) VALUES ('Brazil', 'BRA');
INSERT INTO countries (name, code) VALUES ('Brunei Darussalam', 'BRN');
INSERT INTO countries (name, code) VALUES ('Bulgaria', 'BGR');
INSERT INTO countries (name, code) VALUES ('Burkina Faso', 'BFA');
INSERT INTO countries (name, code) VALUES ('Burundi', 'BDI');
INSERT INTO countries (name, code) VALUES ('Cabo Verde', 'CPV');
INSERT INTO countries (name, code) VALUES ('Cambodia', 'KHM');
INSERT INTO countries (name, code) VALUES ('Cameroon', 'CMR');
INSERT INTO countries (name, code) VALUES ('Canada', 'CAN');
INSERT INTO countries (name, code) VALUES ('Central African Republic', 'CAF');
INSERT INTO countries (name, code) VALUES ('Chad', 'TCD');
INSERT INTO countries (name, code) VALUES ('Chile', 'CHL');
INSERT INTO countries (name, code) VALUES ('China', 'CHN');
INSERT INTO countries (name, code) VALUES ('Colombia', 'COL');
INSERT INTO countries (name, code) VALUES ('Comoros', 'COM');
INSERT INTO countries (name, code) VALUES ('Congo', 'COG');
INSERT INTO countries (name, code) VALUES ('Congo, Democratic Republic of the', 'COD');
INSERT INTO countries (name, code) VALUES ('Costa Rica', 'CRI');
INSERT INTO countries (name, code) VALUES ('Croatia', 'HRV');
INSERT INTO countries (name, code) VALUES ('Cuba', 'CUB');
INSERT INTO countries (name, code) VALUES ('Cyprus', 'CYP');
INSERT INTO countries (name, code) VALUES ('Czech Republic', 'CZE');
INSERT INTO countries (name, code) VALUES ('Denmark', 'DNK');
INSERT INTO countries (name, code) VALUES ('Djibouti', 'DJI');
INSERT INTO countries (name, code) VALUES ('Dominica', 'DMA');
INSERT INTO countries (name, code) VALUES ('Dominican Republic', 'DOM');
INSERT INTO countries (name, code) VALUES ('Ecuador', 'ECU');
INSERT INTO countries (name, code) VALUES ('Egypt', 'EGY');
INSERT INTO countries (name, code) VALUES ('El Salvador', 'SLV');
INSERT INTO countries (name, code) VALUES ('Equatorial Guinea', 'GNQ');
INSERT INTO countries (name, code) VALUES ('Eritrea', 'ERI');
INSERT INTO countries (name, code) VALUES ('Estonia', 'EST');
INSERT INTO countries (name, code) VALUES ('Eswatini', 'SWZ');
INSERT INTO countries (name, code) VALUES ('Ethiopia', 'ETH');
INSERT INTO countries (name, code) VALUES ('Fiji', 'FJI');
INSERT INTO countries (name, code) VALUES ('Finland', 'FIN');
INSERT INTO countries (name, code) VALUES ('France', 'FRA');
INSERT INTO countries (name, code) VALUES ('Gabon', 'GAB');
INSERT INTO countries (name, code) VALUES ('Gambia', 'GMB');
INSERT INTO countries (name, code) VALUES ('Georgia', 'GEO');
INSERT INTO countries (name, code) VALUES ('Germany', 'DEU');
INSERT INTO countries (name, code) VALUES ('Ghana', 'GHA');
INSERT INTO countries (name, code) VALUES ('Greece', 'GRC');
INSERT INTO countries (name, code) VALUES ('Grenada', 'GRD');
INSERT INTO countries (name, code) VALUES ('Guatemala', 'GTM');
INSERT INTO countries (name, code) VALUES ('Guinea', 'GIN');
INSERT INTO countries (name, code) VALUES ('Guinea-Bissau', 'GNB');
INSERT INTO countries (name, code) VALUES ('Guyana', 'GUY');
INSERT INTO countries (name, code) VALUES ('Haiti', 'HTI');
INSERT INTO countries (name, code) VALUES ('Honduras', 'HND');
INSERT INTO countries (name, code) VALUES ('Hungary', 'HUN');
INSERT INTO countries (name, code) VALUES ('Iceland', 'ISL');
INSERT INTO countries (name, code) VALUES ('India', 'IND');
INSERT INTO countries (name, code) VALUES ('Indonesia', 'IDN');
INSERT INTO countries (name, code) VALUES ('Iran (Islamic Republic of)', 'IRN');
INSERT INTO countries (name, code) VALUES ('Iraq', 'IRQ');
INSERT INTO countries (name, code) VALUES ('Ireland', 'IRL');
INSERT INTO countries (name, code) VALUES ('Israel', 'ISR');
INSERT INTO countries (name, code) VALUES ('Italy', 'ITA');
INSERT INTO countries (name, code) VALUES ('Jamaica', 'JAM');
INSERT INTO countries (name, code) VALUES ('Japan', 'JPN');
INSERT INTO countries (name, code) VALUES ('Jordan', 'JOR');
INSERT INTO countries (name, code) VALUES ('Kazakhstan', 'KAZ');
INSERT INTO countries (name, code) VALUES ('Kenya', 'KEN');
INSERT INTO countries (name, code) VALUES ('Kiribati', 'KIR');
INSERT INTO countries (name, code) VALUES ('Korea, Democratic People\'s Republic of', 'PRK');
INSERT INTO countries (name, code) VALUES ('Korea, Republic of', 'KOR');
INSERT INTO countries (name, code) VALUES ('Kuwait', 'KWT');
INSERT INTO countries (name, code) VALUES ('Kyrgyzstan', 'KGZ');
INSERT INTO countries (name, code) VALUES ('Lao People\'s Democratic Republic', 'LAO');
INSERT INTO countries (name, code) VALUES ('Latvia', 'LVA');
INSERT INTO countries (name, code) VALUES ('Lebanon', 'LBN');
INSERT INTO countries (name, code) VALUES ('Lesotho', 'LSO');
INSERT INTO countries (name, code) VALUES ('Liberia', 'LBR');
INSERT INTO countries (name, code) VALUES ('Libya', 'LBY');
INSERT INTO countries (name, code) VALUES ('Liechtenstein', 'LIE');
INSERT INTO countries (name, code) VALUES ('Lithuania', 'LTU');
INSERT INTO countries (name, code) VALUES ('Luxembourg', 'LUX');
INSERT INTO countries (name, code) VALUES ('Madagascar', 'MDG');
INSERT INTO countries (name, code) VALUES ('Malawi', 'MWI');
INSERT INTO countries (name, code) VALUES ('Malaysia', 'MYS');
INSERT INTO countries (name, code) VALUES ('Maldives', 'MDV');
INSERT INTO countries (name, code) VALUES ('Mali', 'MLI');
INSERT INTO countries (name, code) VALUES ('Malta', 'MLT');
INSERT INTO countries (name, code) VALUES ('Marshall Islands', 'MHL');
INSERT INTO countries (name, code) VALUES ('Mauritania', 'MRT');
INSERT INTO countries (name, code) VALUES ('Mauritius', 'MUS');
INSERT INTO countries (name, code) VALUES ('Mexico', 'MEX');
INSERT INTO countries (name, code) VALUES ('Micronesia (Federated States of)', 'FSM');
INSERT INTO countries (name, code) VALUES ('Moldova (Republic of)', 'MDA');
INSERT INTO countries (name, code) VALUES ('Monaco', 'MCO');
INSERT INTO countries (name, code) VALUES ('Mongolia', 'MNG');
INSERT INTO countries (name, code) VALUES ('Montenegro', 'MNE');
INSERT INTO countries (name, code) VALUES ('Morocco', 'MAR');
INSERT INTO countries (name, code) VALUES ('Mozambique', 'MOZ');
INSERT INTO countries (name, code) VALUES ('Myanmar', 'MMR');
INSERT INTO countries (name, code) VALUES ('Namibia', 'NAM');
INSERT INTO countries (name, code) VALUES ('Nauru', 'NRU');
INSERT INTO countries (name, code) VALUES ('Nepal', 'NPL');
INSERT INTO countries (name, code) VALUES ('Netherlands', 'NLD');
INSERT INTO countries (name, code) VALUES ('New Zealand', 'NZL');
INSERT INTO countries (name, code) VALUES ('Nicaragua', 'NIC');
INSERT INTO countries (name, code) VALUES ('Niger', 'NER');
INSERT INTO countries (name, code) VALUES ('Nigeria', 'NGA');
INSERT INTO countries (name, code) VALUES ('North Macedonia', 'MKD');
INSERT INTO countries (name, code) VALUES ('Norway', 'NOR');
INSERT INTO countries (name, code) VALUES ('Oman', 'OMN');
INSERT INTO countries (name, code) VALUES ('Pakistan', 'PAK');
INSERT INTO countries (name, code) VALUES ('Palau', 'PLW');
INSERT INTO countries (name, code) VALUES ('Panama', 'PAN');
INSERT INTO countries (name, code) VALUES ('Papua New Guinea', 'PNG');
INSERT INTO countries (name, code) VALUES ('Paraguay', 'PRY');
INSERT INTO countries (name, code) VALUES ('Peru', 'PER');
INSERT INTO countries (name, code) VALUES ('Philippines', 'PHL');
INSERT INTO countries (name, code) VALUES ('Poland', 'POL');
INSERT INTO countries (name, code) VALUES ('Portugal', 'PRT');
INSERT INTO countries (name, code) VALUES ('Qatar', 'QAT');
INSERT INTO countries (name, code) VALUES ('Romania', 'ROU');
INSERT INTO countries (name, code) VALUES ('Russian Federation', 'RUS');
INSERT INTO countries (name, code) VALUES ('Rwanda', 'RWA');
INSERT INTO countries (name, code) VALUES ('Saint Kitts and Nevis', 'KNA');
INSERT INTO countries (name, code) VALUES ('Saint Lucia', 'LCA');
INSERT INTO countries (name, code) VALUES ('Saint Vincent and the Grenadines', 'VCT');
INSERT INTO countries (name, code) VALUES ('Samoa', 'WSM');
INSERT INTO countries (name, code) VALUES ('San Marino', 'SMR');
INSERT INTO countries (name, code) VALUES ('Sao Tome and Principe', 'STP');
INSERT INTO countries (name, code) VALUES ('Saudi Arabia', 'SAU');
INSERT INTO countries (name, code) VALUES ('Senegal', 'SEN');
INSERT INTO countries (name, code) VALUES ('Serbia', 'SRB');
INSERT INTO countries (name, code) VALUES ('Seychelles', 'SYC');
INSERT INTO countries (name, code) VALUES ('Sierra Leone', 'SLE');
INSERT INTO countries (name, code) VALUES ('Singapore', 'SGP');
INSERT INTO countries (name, code) VALUES ('Slovakia', 'SVK');
INSERT INTO countries (name, code) VALUES ('Slovenia', 'SVN');
INSERT INTO countries (name, code) VALUES ('Solomon Islands', 'SLB');
INSERT INTO countries (name, code) VALUES ('Somalia', 'SOM');
INSERT INTO countries (name, code) VALUES ('South Africa', 'ZAF');
INSERT INTO countries (name, code) VALUES ('South Sudan', 'SSD');
INSERT INTO countries (name, code) VALUES ('Spain', 'ESP');
INSERT INTO countries (name, code) VALUES ('Sri Lanka', 'LKA');
INSERT INTO countries (name, code) VALUES ('Sudan', 'SDN');
INSERT INTO countries (name, code) VALUES ('Suriname', 'SUR');
INSERT INTO countries (name, code) VALUES ('Sweden', 'SWE');
INSERT INTO countries (name, code) VALUES ('Switzerland', 'CHE');
INSERT INTO countries (name, code) VALUES ('Syrian Arab Republic', 'SYR');
INSERT INTO countries (name, code) VALUES ('Tajikistan', 'TJK');
INSERT INTO countries (name, code) VALUES ('Tanzania, United Republic of', 'TZA');
INSERT INTO countries (name, code) VALUES ('Thailand', 'THA');
INSERT INTO countries (name, code) VALUES ('Timor-Leste', 'TLS');
INSERT INTO countries (name, code) VALUES ('Togo', 'TGO');
INSERT INTO countries (name, code) VALUES ('Tonga', 'TON');
INSERT INTO countries (name, code) VALUES ('Trinidad and Tobago', 'TTO');
INSERT INTO countries (name, code) VALUES ('Tunisia', 'TUN');
INSERT INTO countries (name, code) VALUES ('Turkey', 'TUR');
INSERT INTO countries (name, code) VALUES ('Turkmenistan', 'TKM');
INSERT INTO countries (name, code) VALUES ('Tuvalu', 'TUV');
INSERT INTO countries (name, code) VALUES ('Uganda', 'UGA');
INSERT INTO countries (name, code) VALUES ('Ukraine', 'UKR');
INSERT INTO countries (name, code) VALUES ('United Arab Emirates', 'ARE');
INSERT INTO countries (name, code) VALUES ('United Kingdom of Great Britain and Northern Ireland', 'GBR');
INSERT INTO countries (name, code) VALUES ('United States of America', 'USA');
INSERT INTO countries (name, code) VALUES ('Uruguay', 'URY');
INSERT INTO countries (name, code) VALUES ('Uzbekistan', 'UZB');
INSERT INTO countries (name, code) VALUES ('Vanuatu', 'VUT');
INSERT INTO countries (name, code) VALUES ('Venezuela (Bolivarian Republic of)', 'VEN');
INSERT INTO countries (name, code) VALUES ('Viet Nam', 'VNM');
INSERT INTO countries (name, code) VALUES ('Yemen', 'YEM');
INSERT INTO countries (name, code) VALUES ('Zambia', 'ZMB');
INSERT INTO countries (name, code) VALUES ('Zimbabwe', 'ZWE');
