# Two decimal currencies
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('United States Dollar', '$', 'usd', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('United Arab Emirates Dirham', 'د.إ', 'aed', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Afghan Afghani', '؋', 'afn', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Albanian Lek', 'L', 'all', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Armenian Dram', '֏', 'amd', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Netherlands Antillean Guilder', 'ƒ', 'ang', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Angolan Kwanza', 'Kz', 'aoa', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Argentine Peso', '$', 'ars', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Australian Dollar', '$', 'aud', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Aruban Florin', 'ƒ', 'awg', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Azerbaijani Manat', '₼', 'azn', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Bosnia and Herzegovina Convertible Mark', 'KM', 'bam', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Barbadian Dollar', '$', 'bbd', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Bangladeshi Taka', '৳', 'bdt', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Bulgarian Lev', 'лв', 'bgn', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Bermudian Dollar', '$', 'bmd', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Brunei Dollar', '$', 'bnd', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Bolivian Boliviano', 'Bs.', 'bob', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Brazilian Real', 'R$', 'brl', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Bahamian Dollar', '$', 'bsd', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Botswana Pula', 'P', 'bwp', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Belarusian Ruble', 'Br', 'byn', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Belize Dollar', '$', 'bzd', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Canadian Dollar', '$', 'cad', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Congolese Franc', 'FC', 'cdf', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Swiss Franc', 'Fr', 'chf', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Chinese Yuan', '¥', 'cny', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Colombian Peso', '$', 'cop', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Costa Rican Colón', '₡', 'crc', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Cape Verdean Escudo', '$', 'cve', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Czech Koruna', 'Kč', 'czk', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Danish Krone', 'kr', 'dkk', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Dominican Peso', '$', 'dop', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Algerian Dinar', 'د.ج', 'dzd', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Egyptian Pound', 'ج.م', 'egp', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Ethiopian Birr', 'Br', 'etb', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Euro', '€', 'eur', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Fijian Dollar', '$', 'fjd', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Falkland Islands Pound', '£', 'fkp', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('British Pound', '£', 'gbp', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Georgian Lari', '₾', 'gel', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Gibraltar Pound', '£', 'gip', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Gambian Dalasi', 'D', 'gmd', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Guyanaese Dollar', '$', 'gyd', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Hong Kong Dollar', '$', 'hkd', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Honduran Lempira', 'L', 'hnl', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Haitian Gourde', 'G', 'htg', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Israeli New Shekel', '₪', 'ils', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Indian Rupee', '₹', 'inr', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Jamaican Dollar', '$', 'jmd', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Kenyan Shilling', 'Sh', 'kes', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Kyrgyzstani Som', 'лв', 'kgs', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Cambodian Riel', '៛', 'khr', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Cayman Islands Dollar', '$', 'kyd', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Kazakhstani Tenge', '₸', 'kzt', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Lebanese Pound', 'ل.ل', 'lbp', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Sri Lankan Rupee', 'Rs', 'lkr', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Liberian Dollar', '$', 'lrd', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Lesotho Loti', 'L', 'lsl', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Moroccan Dirham', 'د.م.', 'mad', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Moldovan Leu', 'L', 'mdl', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Macedonian Denar', 'ден', 'mkd', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Myanmar Kyat', 'K', 'mmk', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Mongolian Tögrög', '₮', 'mnt', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Macanese Pataca', 'P', 'mop', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Maldivian Rufiyaa', 'Rf', 'mvr', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Malaysian Ringgit', 'RM', 'myr', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Mozambican Metical', 'MT', 'mzn', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Namibian Dollar', '$', 'nad', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Nigerian Naira', '₦', 'ngn', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Norwegian Krone', 'kr', 'nok', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Nepalese Rupee', '₨', 'npr', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('New Zealand Dollar', '$', 'nzd', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Panamanian Balboa', 'B/.', 'pab', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Peruvian Sol', 'S/.', 'pen', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Papua New Guinean Kina', 'K', 'pgk', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Philippine Peso', '₱', 'php', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Pakistani Rupee', '₨', 'pkr', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Polish Złoty', 'zł', 'pln', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Qatari Riyal', 'ر.ق', 'qar', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Romanian Leu', 'lei', 'ron', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Serbian Dinar', 'дин.', 'rsd', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Russian Ruble', '₽', 'rub', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Saudi Riyal', 'ر.س', 'sar', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Solomon Islands Dollar', '$', 'sbd', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Seychellois Rupee', '₨', 'scr', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Swedish Krona', 'kr', 'sek', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Singapore Dollar', '$', 'sgd', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Sierra Leonean Leone', 'Le', 'sle', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Somali Shilling', 'Sh', 'sos', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('South Sudanese Pound', '£', 'ssp', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Swazi Lilangeni', 'L', 'szl', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Thai Baht', '฿', 'thb', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Tajikistani Somoni', 'ЅМ', 'tjs', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Tongan Paʻanga', 'T$', 'top', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Turkish Lira', '₺', 'try', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Trinidad and Tobago Dollar', '$', 'ttd', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Ukrainian Hryvnia', '₴', 'uah', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('United States Dollar', '$', 'usd', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Uruguayan Peso', '$', 'uyu', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Uzbekistani Som', 'сўм', 'uzs', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Vietnamese Dong', '₫', 'vnd', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Vanuatu Vatu', 'Vt', 'vuv', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Samoan Tala', 'T', 'wst', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('East Caribbean Dollar', '$', 'xcd', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Yemeni Rial', '﷼', 'yer', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('South African Rand', 'R', 'zar', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Zambian Kwacha', 'ZK', 'zmw', 100);

# Zero-Decimal Currencies
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Burundian Franc', 'FBu', 'bif', 1);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Chilean Peso', '$', 'clp', 1);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Djiboutian Franc', 'Fdj', 'djf', 1);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Guinean Franc', 'FG', 'gnf', 1);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Japanese Yen', '¥', 'jpy', 1);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Cambodian Riel', '៛', 'khr', 1);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Comorian Franc', 'CF', 'kmf', 1);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('South Korean Won', '₩', 'krw', 1);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Mongolian Tugrik', '₮', 'mnt', 1);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Paraguayan Guaraní', '₲', 'pyg', 1);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Rwandan Franc', 'FRw', 'rwf', 1);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Ugandan Shilling', 'USh', 'ugx', 1);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Vietnamese Dong', '₫', 'vnd', 1);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Vanuatu Vatu', 'Vt', 'vuv', 1);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Central African CFA Franc', 'FCFA', 'xaf', 1);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('West African CFA Franc', 'CFA', 'xof', 1);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('CFP Franc', '₣', 'xpf', 1);

# Three-Decimal Currencies
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Bahraini Dinar', 'BD', 'bhd', 1000);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Jordanian Dinar', 'JD', 'jod', 1000);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Kuwaiti Dinar', 'KD', 'kwd', 1000);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Omani Rial', 'ر.ع.', 'omr', 1000);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Tunisian Dinar', 'DT', 'tnd', 1000);

# Special cases - on manual payouts
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Icelandic Króna', 'kr', 'isk', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Hungarian Forint', 'Ft', 'huf', 1);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('New Taiwan Dollar', 'NT$', 'twd', 1);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Ugandan Shilling', 'USh', 'ugx', 1);