INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Afghan Afghani', '؋', 'AFN', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Euro', '€', 'EUR', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Albanian Lek', 'L', 'ALL', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Algerian Dinar', 'دج', 'DZD', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('United States Dollar', '$', 'USD', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('East Caribbean Dollar', '$', 'XCD', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Argentine Peso', '$', 'ARS', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Armenian Dram', '֏', 'AMD', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Aruban Florin', 'ƒ', 'AWG', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Australian Dollar', '$', 'AUD', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Azerbaijani Manat', '₼', 'AZN', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Bahamian Dollar', '$', 'BSD', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Bahraini Dinar', '.د.ب', 'BHD', 1000);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Bangladeshi Taka', '৳', 'BDT', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Barbadian Dollar', '$', 'BBD', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Belarusian Ruble', 'Br', 'BYN', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Belize Dollar', '$', 'BZD', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('West African CFA franc', 'Fr', 'XOF', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Bermudian Dollar', '$', 'BMD', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Bhutanese Ngultrum', 'Nu.', 'BTN', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Bolivian Boliviano', 'Bs.', 'BOB', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Bosnia and Herzegovina Convertible Mark', 'KM', 'BAM', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Botswana Pula', 'P', 'BWP', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Brazilian Real', 'R$', 'BRL', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Brunei Dollar', '$', 'BND', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Bulgarian Lev', 'лв', 'BGN', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Burundi Franc', 'Fr', 'BIF', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Cambodian Riel', '៛', 'KHR', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Canadian Dollar', '$', 'CAD', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Cape Verdean Escudo', 'Esc', 'CVE', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Cayman Islands Dollar', '$', 'KYD', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Central African CFA franc', 'Fr', 'XAF', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Chilean Peso', '$', 'CLP', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Chinese Yuan', '¥', 'CNY', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Colombian Peso', '$', 'COP', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Comorian Franc', 'Fr', 'KMF', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Congolese Franc', 'Fr', 'CDF', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Costa Rican Colón', '₡', 'CRC', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Croatian Kuna', 'kn', 'HRK', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Cuban Peso', '$', 'CUP', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Czech Koruna', 'Kč', 'CZK', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Danish Krone', 'kr', 'DKK', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Djiboutian Franc', 'Fr', 'DJF', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Dominican Peso', 'RD$', 'DOP', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Egyptian Pound', '£', 'EGP', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Eritrean Nakfa', 'Nfk', 'ERN', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Ethiopian Birr', 'Br', 'ETB', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Falkland Islands Pound', '£', 'FKP', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Fijian Dollar', '$', 'FJD', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Gambian Dalasi', 'D', 'GMD', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Georgian Lari', 'ლ', 'GEL', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Ghanaian Cedi', '₵', 'GHS', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Gibraltar Pound', '£', 'GIP', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Guatemalan Quetzal', 'Q', 'GTQ', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Guinean Franc', 'Fr', 'GNF', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Guyanese Dollar', '$', 'GYD', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Haitian Gourde', 'G', 'HTG', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Honduran Lempira', 'L', 'HNL', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Hong Kong Dollar', '$', 'HKD', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Hungarian Forint', 'Ft', 'HUF', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Icelandic Króna', 'kr', 'ISK', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Indian Rupee', '₹', 'INR', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Indonesian Rupiah', 'Rp', 'IDR', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Iranian Rial', '﷼', 'IRR', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Iraqi Dinar', 'ع.د', 'IQD', 1000);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Israeli New Shekel', '₪', 'ILS', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Jamaican Dollar', '$', 'JMD', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Japanese Yen', '¥', 'JPY', 1);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Jordanian Dinar', 'د.ا', 'JOD', 1000);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Kazakhstani Tenge', '₸', 'KZT', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Kenyan Shilling', 'Sh', 'KES', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Kuwaiti Dinar', 'د.ك', 'KWD', 1000);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Kyrgyzstani Som', 'с', 'KGS', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Lao Kip', '₭', 'LAK', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Lebanese Pound', 'ل.ل', 'LBP', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Lesotho Loti', 'L', 'LSL', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Liberian Dollar', '$', 'LRD', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Libyan Dinar', 'ل.د', 'LYD', 1000);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Macanese Pataca', 'P', 'MOP', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Malagasy Ariary', 'Ar', 'MGA', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Malawian Kwacha', 'MK', 'MWK', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Malaysian Ringgit', 'RM', 'MYR', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Maldivian Rufiyaa', 'Rf', 'MVR', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Mauritanian Ouguiya', 'UM', 'MRU', 5);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Mauritian Rupee', '₨', 'MUR', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Mexican Peso', '$', 'MXN', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Moldovan Leu', 'L', 'MDL', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Mongolian Tögrög', '₮', 'MNT', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Moroccan Dirham', 'د.م.', 'MAD', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Mozambican Metical', 'MT', 'MZN', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Namibian Dollar', '$', 'NAD', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Nepalese Rupee', '₨', 'NPR', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Netherlands Antillean Guilder', 'ƒ', 'ANG', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('New Zealand Dollar', '$', 'NZD', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Nicaraguan Córdoba', 'C$', 'NIO', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Nigerian Naira', '₦', 'NGN', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Norwegian Krone', 'kr', 'NOK', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Omani Rial', 'ر.ع.', 'OMR', 1000);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Pakistani Rupee', '₨', 'PKR', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Panamanian Balboa', 'B/.', 'PAB', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Papua New Guinean Kina', 'K', 'PGK', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Paraguayan Guaraní', '₲', 'PYG', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Peruvian Sol', 'S/', 'PEN', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Philippine Peso', '₱', 'PHP', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Polish Złoty', 'zł', 'PLN', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Qatari Riyal', 'ر.ق', 'QAR', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Romanian Leu', 'lei', 'RON', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Russian Ruble', '₽', 'RUB', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Rwandan Franc', 'Fr', 'RWF', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Saint Helena Pound', '£', 'SHP', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Samoan Tālā', 'T', 'WST', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('São Tomé and Príncipe Dobra', 'Db', 'STN', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Saudi Riyal', 'ر.س', 'SAR', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Serbian Dinar', 'дин.', 'RSD', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Seychellois Rupee', '₨', 'SCR', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Sierra Leonean Leone', 'Le', 'SLL', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Singapore Dollar', '$', 'SGD', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Solomon Islands Dollar', '$', 'SBD', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Somali Shilling', 'Sh', 'SOS', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('South African Rand', 'R', 'ZAR', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('South Sudanese Pound', '£', 'SSP', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Sri Lankan Rupee', '₨', 'LKR', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Sudanese Pound', 'ج.س.', 'SDG', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Surinamese Dollar', '$', 'SRD', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Swazi Lilangeni', 'L', 'SZL', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Swedish Krona', 'kr', 'SEK', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Swiss Franc', 'Fr', 'CHF', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Syrian Pound', '£', 'SYP', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('New Taiwan Dollar', 'NT$', 'TWD', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Tajikistani Somoni', 'ЅМ', 'TJS', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Tanzanian Shilling', 'Sh', 'TZS', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Thai Baht', '฿', 'THB', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Tongan Paʻanga', 'T$', 'TOP', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Trinidad and Tobago Dollar', '$', 'TTD', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Tunisian Dinar', 'د.ت', 'TND', 1000);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Turkish Lira', '₺', 'TRY', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Turkmenistani Manat', 'm', 'TMT', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Ugandan Shilling', 'Sh', 'UGX', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Ukrainian Hryvnia', '₴', 'UAH', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('United Arab Emirates Dirham', 'د.إ', 'AED', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Uruguayan Peso', '$', 'UYU', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Uzbekistani Soʻm', 'soʻm', 'UZS', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Vanuatu Vatu', 'VT', 'VUV', 1);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Venezuelan Bolívar', 'Bs', 'VES', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Vietnamese Đồng', '₫', 'VND', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Yemeni Rial', '﷼', 'YER', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Zambian Kwacha', 'ZK', 'ZMW', 100);
INSERT INTO currencies (name, symbol, code, unit_amount) VALUES ('Zimbabwean Dollar', '$', 'ZWL', 100);
