INSERT INTO users (email, enabled, first_name, last_name, user_password, main_image)
VALUES ('admin@example.com', 1, 'John', 'Doe', '$2a$12$GtMRozUsL6C/2J5CIc8teeebj7HhkO.OiPlbT51jp2UMe.zWiG1Cq', 'john_doe.jpg'),
       ('jane.doe@example.com', 1, 'Jane', 'Doe', '$2a$12$F8T7zDCYG/L78t/YpCJnfeYeyiCWpQn.5c6ps31qP5pZU8PyJyOtu', 'jane_doe.jpg'),
       ('alice@example.com', 0, 'Alice', 'Smith', '$2a$12$fdgvTe/1nMI02zDGQY8sse9tY0ND6fhPT7wZ.41zsbqRnU5eemVGm', 'alice_smith.jpg'),
       ('bob@example.com', 1, 'Bob', 'Johnson', '$2a$12$EuRYn5OABykvieaONIQrcuJhXADwONbcYvqVlaUDVrqz4n2MsS6l6', 'bob_johnson.jpg'),
       ('charlie@example.com', 1, 'Charlie', 'Brown', '$2a$12$gjdjoJvGk5kTBjpNEytu/e575itQD.X1cfQLkiGFJxKDa7DiYzY3W', 'charlie_brown.jpg'),
       ('david@example.com', 0, 'David', 'Wilson', '$2a$12$XyF7l7Uxi7U6JyXWfa6mUexcJe6zGNzCh1nmvXGLYhAE.8l.ZWyka', 'david_wilson.jpg'),
       ('eva@example.com', 1, 'Eva', 'Davis', '$2a$12$kMH/0LGXn2q/g.bsD3I.WORG2dw4LtxQs4CqamlO3KPG.FsMqxsUi', 'eva_davis.jpg'),
       ('frank@example.com', 1, 'Frank', 'Martinez', '$2a$12$lD/VNSzHxmg7GGBARQHbF.mUd7wByIzmk8Gw19nseU.g1uF6TRkCG', 'frank_martinez.jpg'),
       ('grace@example.com', 1, 'Grace', 'Garcia', '$2a$12$QWLymfe2KUDkxuGxJGCuueQhjTrpIsHB.Alqv.K3n9pBSl2cGxgfS', 'grace_garcia.jpg'),
       ('harry@example.com', 1, 'Harry', 'Lee', '$2a$12$1dj3x6dMJcV.uggiUQaqbubEDiEaagzf4VD/yTd5uttczNN0eXSqK', 'harry_lee.jpg'),
       ('isabella@example.com', 1, 'Isabella', 'Clark', '$2a$12$6EVhDwP/6/VOivSMhKVkgO3YkWKzlr2XsizTZhVoFcojm3XsZuPf6', 'isabella_clark.jpg'),
       ('jackson@example.com', 0, 'Jackson', 'Lewis', '$2a$12$alYl0.FEJwGI1HcZxdn6S.HkS2CIJk4MuKmmqU/m2vn720ym6hv7y', 'jackson_lewis.jpg'),
       ('karen@example.com', 1, 'Karen', 'Robinson', '$2a$12$tM./xUCWOvXg247NpI5YSOj0hLjA/wNLAztCecarMOimLgBkkNM4a', 'karen_robinson.jpg'),
       ('larry@example.com', 1, 'Larry', 'Walker', '$2a$12$N/KaeA.Bq0GMv.810vKIt.EGsSka.vQ4p6sRzIIgkvwy3P5OG8Ppe', 'larry_walker.jpg'),
       ('mary@example.com', 1, 'Mary', 'Young', '$2a$12$AihonyqLXOdyllJg5N/fQOEUsMZz1h5YDllbcGet.nw2QEfMOfZJ2', 'mary_young.jpg'),
       ('nick@example.com', 1, 'Nick', 'King', '$2a$12$s186IX4968oxjfBCjQSyJegxUZ8kh0AcZDz04I2FtVuCrCKiX8y/y', 'nick_king.jpg'),
       ('olivia@example.com', 0, 'Olivia', 'Wright', '$2a$12$vwbbonJkt4f.V8bZ71eLjOdjhqEJ0JEx3OOh700p.k57yl/U9nQ3C', 'olivia_wright.jpg'),
       ('paul@example.com', 1, 'Paul', 'Scott', '$2a$12$4Od7mVeJTgjtqhtEruqiYuv/3YCTugYVZWejR81J1esb47LQxLehG', 'paul_scott.jpg'),
       ('quinn@example.com', 1, 'Quinn', 'Green', '$2a$12$FBylG1iTXq6fYzFF3Qp9Eexk8jH/o7BnvVp6/mKnsY4mdYdQGcic6', 'quinn_green.jpg'),
       ('rachel@example.com', 1, 'Rachel', 'Adams', '$2a$12$03V1ZNrZq1luOu2pjZhP6ueK.JZf1PZC30abUiAi3eOVChQ1VcGHG', 'rachel_adams.jpg'),
       ('steve@example.com', 1, 'Steve', 'Baker', '$2a$12$qDjABk0ftN/besdD5xczDO2GDvw0RM3Nuw9cN.WTJlW9VHHpr01BW', 'steve_baker.jpg'),
       ('tina@example.com', 0, 'Tina', 'Nelson', '$2a$12$qDjABk0ftN/besdD5xczDO2GDvw0RM3Nuw9cN.WTJlW9VHHpr01BW', 'tina_nelson.jpg'),
       ('uma@example.com', 1, 'Uma', 'Carter', '$2a$12$YqgRpB9RCyPHnP.i7IhtKuOdI7zY.0VO73jOhwBgxPA8FVq33H786', 'uma_carter.jpg');